# fly.toml file generated for auroradysis-rsshub-redis on 2023-02-01T10:50:24Z

app = "auroradysis-rsshub-redis"

[metrics]
  port = 9091
  path = "/metrics"

# Uncomment these lines for public internet access to Redis on port 10000
#
# [[services]]
# internal_port = 6379
# protocol      = "tcp"

#   [[services.ports]]
#   port     = "10000"

#   [[services.tcp_checks]]
#   interval = 10000
#   timeout  = 2000
